name: Slither Static Analysis

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crytic/slither-action@v0.4.1
